"""make_project_id_nullable_and_add_developer_id

Revision ID: 0af83c947fdb
Revises: 398f54aa2093
Create Date: 2026-03-31 12:21:51.344004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af83c947fdb'
down_revision: Union[str, Sequence[str], None] = '398f54aa2093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_lot', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.alter_column('extraction_lot', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_lot_developer_period', 'extraction_lot', ['developer_id', 'period_id'], unique=False)
    op.create_foreign_key(None, 'extraction_lot', 'developer', ['developer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extraction_lot', type_='foreignkey')
    op.alter_column('extraction_lot', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('extraction_lot', 'developer_id')
    # ### end Alembic commands ###
