"""initial_schema

Revision ID: 126d02920e38
Revises: 6f89c6bdd578
Create Date: 2026-03-17 14:32:28.860986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '126d02920e38'
down_revision: Union[str, Sequence[str], None] = '6f89c6bdd578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('alert', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_alert_acknowledged_by', table_name='alert')
    op.drop_index('ix_alert_id', table_name='alert')
    op.drop_index('ix_alert_is_resolved', table_name='alert')
    op.drop_index('ix_alert_kpi_snapshot_id', table_name='alert')
    op.drop_index('ix_alert_level', table_name='alert')
    op.drop_index('ix_alert_threshold_id', table_name='alert')
    op.drop_index('ix_alert_triggered_at', table_name='alert')
    op.create_index('idx_alert_acknowledged_by', 'alert', ['acknowledged_by'], unique=False)
    op.create_index('idx_alert_unresolved_recent', 'alert', ['is_resolved', 'triggered_at'], unique=False)
    op.alter_column('app_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('app_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_app_user_email', table_name='app_user')
    op.drop_index('ix_app_user_id', table_name='app_user')
    op.drop_index('ix_app_user_login', table_name='app_user')
    op.create_unique_constraint(None, 'app_user', ['email'])
    op.create_unique_constraint(None, 'app_user', ['login'])
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_type', table_name='audit_log')
    op.drop_index('ix_audit_log_id', table_name='audit_log')
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.create_index('idx_audit_user_date', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.alter_column('commit_merge_request', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('commit_merge_request', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dashboard', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dashboard', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_dashboard_created_by', table_name='dashboard')
    op.drop_index('ix_dashboard_id', table_name='dashboard')
    op.drop_index('ix_dashboard_project_id', table_name='dashboard')
    op.drop_index('ix_dashboard_site_id', table_name='dashboard')
    op.alter_column('developer', 'is_validated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='False = extrait auto GitLab non encore validé par admin',
               existing_comment='False = extrait auto GitLab, True = valide par admin',
               existing_nullable=False)
    op.alter_column('developer', 'is_bot',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='True = bot détecté automatiquement, exclu de tous les KPIs',
               existing_comment='True = bot detecte auto (exclu des KPIs)',
               existing_nullable=False)
    op.alter_column('developer', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment="Origine : 'gitlab_extraction' | 'manual'",
               existing_comment='gitlab_extraction | manual',
               existing_nullable=False)
    op.alter_column('developer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('developer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_developer_gitlab_project', table_name='developer')
    op.drop_index('idx_developer_group_fk', table_name='developer')
    op.drop_index('ix_developer_created_by', table_name='developer')
    op.drop_index('ix_developer_id', table_name='developer')
    op.drop_index('ix_developer_project_id', table_name='developer')
    op.drop_index('ix_developer_site_id', table_name='developer')
    op.create_index('idx_developer_group', 'developer', ['group_id'], unique=False)
    op.create_index('idx_developer_kpi_filter', 'developer', ['site_id', 'is_validated', 'is_bot', 'is_active'], unique=False)
    op.alter_column('developer_group', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('developer_group', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_developer_group_id', table_name='developer_group')
    op.drop_index('ix_developer_group_manager_id', table_name='developer_group')
    op.drop_index('ix_developer_group_project_id', table_name='developer_group')
    op.drop_index('ix_developer_group_site_id', table_name='developer_group')
    op.alter_column('extraction_lot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('extraction_lot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_extraction_lot_id', table_name='extraction_lot')
    op.drop_index('ix_extraction_lot_period_id', table_name='extraction_lot')
    op.drop_index('ix_extraction_lot_project_id', table_name='extraction_lot')
    op.drop_index('ix_extraction_lot_triggered_by', table_name='extraction_lot')
    op.create_index('idx_lot_triggered_by', 'extraction_lot', ['triggered_by'], unique=False)
    op.alter_column('git_commit', 'additions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('git_commit', 'deletions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('git_commit', 'total_changes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('git_commit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('git_commit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_git_commit_authored_date', table_name='git_commit')
    op.drop_index('ix_git_commit_developer_id', table_name='git_commit')
    op.drop_index('ix_git_commit_extraction_lot_id', table_name='git_commit')
    op.drop_index('ix_git_commit_gitlab_commit_id', table_name='git_commit')
    op.drop_index('ix_git_commit_id', table_name='git_commit')
    op.drop_index('ix_git_commit_project_id', table_name='git_commit')
    op.add_column('gitlab_config', sa.Column('site_id', sa.Integer(), nullable=True))
    op.alter_column('gitlab_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('gitlab_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_gitlab_config_id', table_name='gitlab_config')
    op.create_index('idx_gitlab_config_active', 'gitlab_config', ['is_active'], unique=False)
    op.create_index('idx_gitlab_config_site', 'gitlab_config', ['site_id'], unique=False)
    op.create_foreign_key(None, 'gitlab_config', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.alter_column('kpi_definition', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('kpi_definition', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_kpi_definition_active', table_name='kpi_definition')
    op.drop_index('idx_kpi_definition_code', table_name='kpi_definition')
    op.drop_index('ix_kpi_definition_code', table_name='kpi_definition')
    op.drop_index('ix_kpi_definition_id', table_name='kpi_definition')
    op.create_index('idx_kpi_def_active', 'kpi_definition', ['is_active'], unique=False)
    op.create_index('idx_kpi_def_level', 'kpi_definition', ['aggregation_level'], unique=False)
    op.create_unique_constraint(None, 'kpi_definition', ['code'])
    op.alter_column('kpi_snapshot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('kpi_snapshot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_kpi_project_period_site_group', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_developer_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_group_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_kpi_definition_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_lot_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_period_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_project_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_site_id', table_name='kpi_snapshot')
    op.drop_index('ix_kpi_snapshot_snapshot_date', table_name='kpi_snapshot')
    op.create_index('idx_snapshot_date', 'kpi_snapshot', ['snapshot_date'], unique=False)
    op.create_index('idx_snapshot_developer', 'kpi_snapshot', ['developer_id'], unique=False)
    op.create_index('idx_snapshot_group', 'kpi_snapshot', ['group_id'], unique=False)
    op.create_index('idx_snapshot_lot', 'kpi_snapshot', ['lot_id'], unique=False)
    op.create_index('idx_snapshot_project_period', 'kpi_snapshot', ['project_id', 'period_id'], unique=False)
    op.create_index('idx_snapshot_site', 'kpi_snapshot', ['site_id'], unique=False)
    op.drop_constraint('kpi_snapshot_kpi_definition_id_fkey', 'kpi_snapshot', type_='foreignkey')
    op.drop_column('kpi_snapshot', 'kpi_definition_id')
    op.alter_column('kpi_threshold', 'kpi_definition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kpi_threshold', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('kpi_threshold', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_kpi_threshold_dashboard_kpi', table_name='kpi_threshold')
    op.drop_index('ix_kpi_threshold_created_by', table_name='kpi_threshold')
    op.drop_index('ix_kpi_threshold_dashboard_id', table_name='kpi_threshold')
    op.drop_index('ix_kpi_threshold_id', table_name='kpi_threshold')
    op.drop_index('ix_kpi_threshold_kpi_definition_id', table_name='kpi_threshold')
    op.drop_index('ix_kpi_threshold_project_id', table_name='kpi_threshold')
    op.create_index('idx_kpi_threshold_creator', 'kpi_threshold', ['created_by'], unique=False)
    op.create_index('idx_kpi_threshold_dashboard', 'kpi_threshold', ['dashboard_id'], unique=False)
    op.create_index('idx_kpi_threshold_definition', 'kpi_threshold', ['kpi_definition_id'], unique=False)
    op.create_index('idx_kpi_threshold_project', 'kpi_threshold', ['project_id'], unique=False)
    op.create_index('idx_kpi_threshold_unique', 'kpi_threshold', ['dashboard_id', 'kpi_definition_id', 'type'], unique=True)
    op.drop_constraint('kpi_threshold_kpi_definition_id_fkey', 'kpi_threshold', type_='foreignkey')
    op.create_foreign_key(None, 'kpi_threshold', 'kpi_definition', ['kpi_definition_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('kpi_threshold', 'kpi_name')
    op.alter_column('merge_request', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('merge_request', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_merge_request_created_at_gitlab', table_name='merge_request')
    op.drop_index('ix_merge_request_developer_id', table_name='merge_request')
    op.drop_index('ix_merge_request_extraction_lot_id', table_name='merge_request')
    op.drop_index('ix_merge_request_gitlab_mr_id', table_name='merge_request')
    op.drop_index('ix_merge_request_id', table_name='merge_request')
    op.drop_index('ix_merge_request_project_id', table_name='merge_request')
    op.create_index('idx_mr_approved', 'merge_request', ['approved', 'project_id'], unique=False)
    op.alter_column('period', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('period', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_period_id', table_name='period')
    op.create_index('idx_period_status', 'period', ['status'], unique=False)
    op.create_index('idx_period_year_month', 'period', ['year', 'month'], unique=False)
    op.alter_column('period_filter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('period_filter', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('ix_period_filter_dashboard_id', table_name='period_filter')
    op.drop_index('ix_period_filter_id', table_name='period_filter')
    op.alter_column('project', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('project', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('site', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('site', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_site_name', table_name='site')
    op.drop_index('ix_site_id', table_name='site')
    op.drop_index('ix_site_name', table_name='site')
    op.create_index('idx_site_active', 'site', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'site', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_index('idx_site_active', table_name='site')
    op.create_index('ix_site_name', 'site', ['name'], unique=True)
    op.create_index('ix_site_id', 'site', ['id'], unique=False)
    op.create_index('idx_site_name', 'site', ['name'], unique=False)
    op.alter_column('site', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('site', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('project', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('project', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.create_index('ix_period_filter_id', 'period_filter', ['id'], unique=False)
    op.create_index('ix_period_filter_dashboard_id', 'period_filter', ['dashboard_id'], unique=False)
    op.alter_column('period_filter', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('period_filter', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_index('idx_period_year_month', table_name='period')
    op.drop_index('idx_period_status', table_name='period')
    op.create_index('ix_period_id', 'period', ['id'], unique=False)
    op.alter_column('period', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('period', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_index('idx_mr_approved', table_name='merge_request')
    op.create_index('ix_merge_request_project_id', 'merge_request', ['project_id'], unique=False)
    op.create_index('ix_merge_request_id', 'merge_request', ['id'], unique=False)
    op.create_index('ix_merge_request_gitlab_mr_id', 'merge_request', ['gitlab_mr_id'], unique=False)
    op.create_index('ix_merge_request_extraction_lot_id', 'merge_request', ['extraction_lot_id'], unique=False)
    op.create_index('ix_merge_request_developer_id', 'merge_request', ['developer_id'], unique=False)
    op.create_index('ix_merge_request_created_at_gitlab', 'merge_request', ['created_at_gitlab'], unique=False)
    op.alter_column('merge_request', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('merge_request', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.add_column('kpi_threshold', sa.Column('kpi_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'kpi_threshold', type_='foreignkey')
    op.create_foreign_key('kpi_threshold_kpi_definition_id_fkey', 'kpi_threshold', 'kpi_definition', ['kpi_definition_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_kpi_threshold_unique', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_project', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_definition', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_dashboard', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_creator', table_name='kpi_threshold')
    op.create_index('ix_kpi_threshold_project_id', 'kpi_threshold', ['project_id'], unique=False)
    op.create_index('ix_kpi_threshold_kpi_definition_id', 'kpi_threshold', ['kpi_definition_id'], unique=False)
    op.create_index('ix_kpi_threshold_id', 'kpi_threshold', ['id'], unique=False)
    op.create_index('ix_kpi_threshold_dashboard_id', 'kpi_threshold', ['dashboard_id'], unique=False)
    op.create_index('ix_kpi_threshold_created_by', 'kpi_threshold', ['created_by'], unique=False)
    op.create_index('idx_kpi_threshold_dashboard_kpi', 'kpi_threshold', ['dashboard_id', 'kpi_name'], unique=True)
    op.alter_column('kpi_threshold', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('kpi_threshold', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('kpi_threshold', 'kpi_definition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('kpi_snapshot', sa.Column('kpi_definition_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('kpi_snapshot_kpi_definition_id_fkey', 'kpi_snapshot', 'kpi_definition', ['kpi_definition_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_snapshot_site', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_project_period', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_lot', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_group', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_developer', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_date', table_name='kpi_snapshot')
    op.create_index('ix_kpi_snapshot_snapshot_date', 'kpi_snapshot', ['snapshot_date'], unique=False)
    op.create_index('ix_kpi_snapshot_site_id', 'kpi_snapshot', ['site_id'], unique=False)
    op.create_index('ix_kpi_snapshot_project_id', 'kpi_snapshot', ['project_id'], unique=False)
    op.create_index('ix_kpi_snapshot_period_id', 'kpi_snapshot', ['period_id'], unique=False)
    op.create_index('ix_kpi_snapshot_lot_id', 'kpi_snapshot', ['lot_id'], unique=False)
    op.create_index('ix_kpi_snapshot_kpi_definition_id', 'kpi_snapshot', ['kpi_definition_id'], unique=False)
    op.create_index('ix_kpi_snapshot_id', 'kpi_snapshot', ['id'], unique=False)
    op.create_index('ix_kpi_snapshot_group_id', 'kpi_snapshot', ['group_id'], unique=False)
    op.create_index('ix_kpi_snapshot_developer_id', 'kpi_snapshot', ['developer_id'], unique=False)
    op.create_index('idx_kpi_project_period_site_group', 'kpi_snapshot', ['project_id', 'period_id', 'site_id', 'group_id', 'developer_id'], unique=True)
    op.alter_column('kpi_snapshot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('kpi_snapshot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_constraint(None, 'kpi_definition', type_='unique')
    op.drop_index('idx_kpi_def_level', table_name='kpi_definition')
    op.drop_index('idx_kpi_def_active', table_name='kpi_definition')
    op.create_index('ix_kpi_definition_id', 'kpi_definition', ['id'], unique=False)
    op.create_index('ix_kpi_definition_code', 'kpi_definition', ['code'], unique=True)
    op.create_index('idx_kpi_definition_code', 'kpi_definition', ['code'], unique=False)
    op.create_index('idx_kpi_definition_active', 'kpi_definition', ['is_active'], unique=False)
    op.alter_column('kpi_definition', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('kpi_definition', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_constraint(None, 'gitlab_config', type_='foreignkey')
    op.drop_index('idx_gitlab_config_site', table_name='gitlab_config')
    op.drop_index('idx_gitlab_config_active', table_name='gitlab_config')
    op.create_index('ix_gitlab_config_id', 'gitlab_config', ['id'], unique=False)
    op.alter_column('gitlab_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('gitlab_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_column('gitlab_config', 'site_id')
    op.create_index('ix_git_commit_project_id', 'git_commit', ['project_id'], unique=False)
    op.create_index('ix_git_commit_id', 'git_commit', ['id'], unique=False)
    op.create_index('ix_git_commit_gitlab_commit_id', 'git_commit', ['gitlab_commit_id'], unique=False)
    op.create_index('ix_git_commit_extraction_lot_id', 'git_commit', ['extraction_lot_id'], unique=False)
    op.create_index('ix_git_commit_developer_id', 'git_commit', ['developer_id'], unique=False)
    op.create_index('ix_git_commit_authored_date', 'git_commit', ['authored_date'], unique=False)
    op.alter_column('git_commit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('git_commit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('git_commit', 'total_changes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('git_commit', 'deletions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('git_commit', 'additions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_lot_triggered_by', table_name='extraction_lot')
    op.create_index('ix_extraction_lot_triggered_by', 'extraction_lot', ['triggered_by'], unique=False)
    op.create_index('ix_extraction_lot_project_id', 'extraction_lot', ['project_id'], unique=False)
    op.create_index('ix_extraction_lot_period_id', 'extraction_lot', ['period_id'], unique=False)
    op.create_index('ix_extraction_lot_id', 'extraction_lot', ['id'], unique=False)
    op.alter_column('extraction_lot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('extraction_lot', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.create_index('ix_developer_group_site_id', 'developer_group', ['site_id'], unique=False)
    op.create_index('ix_developer_group_project_id', 'developer_group', ['project_id'], unique=False)
    op.create_index('ix_developer_group_manager_id', 'developer_group', ['manager_id'], unique=False)
    op.create_index('ix_developer_group_id', 'developer_group', ['id'], unique=False)
    op.alter_column('developer_group', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('developer_group', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_index('idx_developer_kpi_filter', table_name='developer')
    op.drop_index('idx_developer_group', table_name='developer')
    op.create_index('ix_developer_site_id', 'developer', ['site_id'], unique=False)
    op.create_index('ix_developer_project_id', 'developer', ['project_id'], unique=False)
    op.create_index('ix_developer_id', 'developer', ['id'], unique=False)
    op.create_index('ix_developer_created_by', 'developer', ['created_by'], unique=False)
    op.create_index('idx_developer_group_fk', 'developer', ['group_id'], unique=False)
    op.create_index('idx_developer_gitlab_project', 'developer', ['gitlab_user_id', 'project_id'], unique=False)
    op.alter_column('developer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('developer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('developer', 'source',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'gitlab_extraction'::character varying"),
               comment='gitlab_extraction | manual',
               existing_comment="Origine : 'gitlab_extraction' | 'manual'",
               existing_nullable=False)
    op.alter_column('developer', 'is_bot',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='True = bot detecte auto (exclu des KPIs)',
               existing_comment='True = bot détecté automatiquement, exclu de tous les KPIs',
               existing_nullable=False)
    op.alter_column('developer', 'is_validated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='False = extrait auto GitLab, True = valide par admin',
               existing_comment='False = extrait auto GitLab non encore validé par admin',
               existing_nullable=False)
    op.create_index('ix_dashboard_site_id', 'dashboard', ['site_id'], unique=False)
    op.create_index('ix_dashboard_project_id', 'dashboard', ['project_id'], unique=False)
    op.create_index('ix_dashboard_id', 'dashboard', ['id'], unique=False)
    op.create_index('ix_dashboard_created_by', 'dashboard', ['created_by'], unique=False)
    op.alter_column('dashboard', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('dashboard', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('commit_merge_request', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('commit_merge_request', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_index('idx_audit_user_date', table_name='audit_log')
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_log_id', 'audit_log', ['id'], unique=False)
    op.create_index('ix_audit_log_entity_type', 'audit_log', ['entity_type'], unique=False)
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.alter_column('audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_constraint(None, 'app_user', type_='unique')
    op.drop_constraint(None, 'app_user', type_='unique')
    op.create_index('ix_app_user_login', 'app_user', ['login'], unique=True)
    op.create_index('ix_app_user_id', 'app_user', ['id'], unique=False)
    op.create_index('ix_app_user_email', 'app_user', ['email'], unique=True)
    op.alter_column('app_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('app_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_index('idx_alert_unresolved_recent', table_name='alert')
    op.drop_index('idx_alert_acknowledged_by', table_name='alert')
    op.create_index('ix_alert_triggered_at', 'alert', ['triggered_at'], unique=False)
    op.create_index('ix_alert_threshold_id', 'alert', ['threshold_id'], unique=False)
    op.create_index('ix_alert_level', 'alert', ['level'], unique=False)
    op.create_index('ix_alert_kpi_snapshot_id', 'alert', ['kpi_snapshot_id'], unique=False)
    op.create_index('ix_alert_is_resolved', 'alert', ['is_resolved'], unique=False)
    op.create_index('ix_alert_id', 'alert', ['id'], unique=False)
    op.create_index('ix_alert_acknowledged_by', 'alert', ['acknowledged_by'], unique=False)
    op.alter_column('alert', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    # ### end Alembic commands ###
