"""initial_schema

Revision ID: 2179b4d0ca54
Revises: 
Create Date: 2026-03-15 17:49:58.899822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2179b4d0ca54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dashboard_access', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_login'), 'app_user', ['login'], unique=True)
    op.create_table('gitlab_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_gitlab_config_id'), 'gitlab_config', ['id'], unique=False)
    op.create_table('kpi_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('formula_description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('aggregation_level', sa.Enum('site', 'project', 'developer', 'group', name='aggregationlevelenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_definition_active', 'kpi_definition', ['is_active'], unique=False)
    op.create_index('idx_kpi_definition_code', 'kpi_definition', ['code'], unique=False)
    op.create_index(op.f('ix_kpi_definition_code'), 'kpi_definition', ['code'], unique=True)
    op.create_index(op.f('ix_kpi_definition_id'), 'kpi_definition', ['id'], unique=False)
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='periodstatusenum'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='chk_period_month_valid'),
    sa.CheckConstraint('year >= 2000', name='chk_period_year_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_period_year_month')
    )
    op.create_index(op.f('ix_period_id'), 'period', ['id'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_country', 'site', ['country'], unique=False)
    op.create_index('idx_site_name', 'site', ['name'], unique=False)
    op.create_index(op.f('ix_site_id'), 'site', ['id'], unique=False)
    op.create_index(op.f('ix_site_name'), 'site', ['name'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'internal', 'public', name='visibilityenum'), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gitlab_config_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['gitlab_config_id'], ['gitlab_config.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_config', 'project', ['gitlab_config_id'], unique=False)
    op.create_index('idx_project_name_namespace', 'project', ['name', 'namespace'], unique=False)
    op.create_index('idx_project_site', 'project', ['site_id'], unique=False)
    op.create_index(op.f('ix_project_gitlab_config_id'), 'project', ['gitlab_config_id'], unique=False)
    op.create_index(op.f('ix_project_gitlab_project_id'), 'project', ['gitlab_project_id'], unique=True)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_site_id'), 'project', ['site_id'], unique=False)
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dashboard_creator', 'dashboard', ['created_by'], unique=False)
    op.create_index('idx_dashboard_project', 'dashboard', ['project_id'], unique=False)
    op.create_index('idx_dashboard_public', 'dashboard', ['is_public'], unique=False)
    op.create_index('idx_dashboard_site', 'dashboard', ['site_id'], unique=False)
    op.create_index(op.f('ix_dashboard_created_by'), 'dashboard', ['created_by'], unique=False)
    op.create_index(op.f('ix_dashboard_id'), 'dashboard', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_project_id'), 'dashboard', ['project_id'], unique=False)
    op.create_index(op.f('ix_dashboard_site_id'), 'dashboard', ['site_id'], unique=False)
    op.create_table('developer_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_devgroup_manager', 'developer_group', ['manager_id'], unique=False)
    op.create_index('idx_devgroup_project_site', 'developer_group', ['project_id', 'site_id'], unique=False)
    op.create_index(op.f('ix_developer_group_id'), 'developer_group', ['id'], unique=False)
    op.create_index(op.f('ix_developer_group_manager_id'), 'developer_group', ['manager_id'], unique=False)
    op.create_index(op.f('ix_developer_group_project_id'), 'developer_group', ['project_id'], unique=False)
    op.create_index(op.f('ix_developer_group_site_id'), 'developer_group', ['site_id'], unique=False)
    op.create_table('extraction_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REALTIME', 'MONTHLY', name='extractiontypeenum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='extractionstatusenum'), nullable=False),
    sa.Column('generated_file', sa.String(length=500), nullable=True),
    sa.Column('md5sum', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lot_period_project', 'extraction_lot', ['period_id', 'project_id'], unique=False)
    op.create_index('idx_lot_type_status', 'extraction_lot', ['type', 'status'], unique=False)
    op.create_index(op.f('ix_extraction_lot_id'), 'extraction_lot', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_lot_period_id'), 'extraction_lot', ['period_id'], unique=False)
    op.create_index(op.f('ix_extraction_lot_project_id'), 'extraction_lot', ['project_id'], unique=False)
    op.create_index(op.f('ix_extraction_lot_triggered_by'), 'extraction_lot', ['triggered_by'], unique=False)
    op.create_table('developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['developer_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_developer_active', 'developer', ['is_active'], unique=False)
    op.create_index('idx_developer_gitlab_project', 'developer', ['gitlab_user_id', 'project_id'], unique=False)
    op.create_index('idx_developer_group_fk', 'developer', ['group_id'], unique=False)
    op.create_index('idx_developer_project', 'developer', ['project_id'], unique=False)
    op.create_index('idx_developer_site', 'developer', ['site_id'], unique=False)
    op.create_index(op.f('ix_developer_created_by'), 'developer', ['created_by'], unique=False)
    op.create_index(op.f('ix_developer_id'), 'developer', ['id'], unique=False)
    op.create_index(op.f('ix_developer_project_id'), 'developer', ['project_id'], unique=False)
    op.create_index(op.f('ix_developer_site_id'), 'developer', ['site_id'], unique=False)
    op.create_table('kpi_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('warning_value', sa.Float(), nullable=False),
    sa.Column('critical_value', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('REALTIME', 'MONTHLY', name='thresholdtypeenum'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.Column('kpi_definition_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_definition_id'], ['kpi_definition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_threshold_dashboard_kpi', 'kpi_threshold', ['dashboard_id', 'kpi_name'], unique=True)
    op.create_index(op.f('ix_kpi_threshold_created_by'), 'kpi_threshold', ['created_by'], unique=False)
    op.create_index(op.f('ix_kpi_threshold_dashboard_id'), 'kpi_threshold', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_kpi_threshold_id'), 'kpi_threshold', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_threshold_kpi_definition_id'), 'kpi_threshold', ['kpi_definition_id'], unique=False)
    op.create_index(op.f('ix_kpi_threshold_project_id'), 'kpi_threshold', ['project_id'], unique=False)
    op.create_table('period_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('realTime', 'lastMonth', 'last3Months', 'last6Months', 'lastYear', 'custom', name='periodfiltertypeenum'), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_period_filter_dashboard', 'period_filter', ['dashboard_id'], unique=False)
    op.create_index('idx_period_filter_type', 'period_filter', ['type'], unique=False)
    op.create_index(op.f('ix_period_filter_dashboard_id'), 'period_filter', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_period_filter_id'), 'period_filter', ['id'], unique=False)
    op.create_table('git_commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_commit_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('authored_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('total_changes', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('extraction_lot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_lot_id'], ['extraction_lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commit_developer_project', 'git_commit', ['developer_id', 'project_id'], unique=False)
    op.create_index('idx_commit_lot', 'git_commit', ['extraction_lot_id'], unique=False)
    op.create_index('idx_commit_project_date', 'git_commit', ['project_id', 'authored_date'], unique=False)
    op.create_index('idx_commit_sha_project', 'git_commit', ['gitlab_commit_id', 'project_id'], unique=True)
    op.create_index(op.f('ix_git_commit_authored_date'), 'git_commit', ['authored_date'], unique=False)
    op.create_index(op.f('ix_git_commit_developer_id'), 'git_commit', ['developer_id'], unique=False)
    op.create_index(op.f('ix_git_commit_extraction_lot_id'), 'git_commit', ['extraction_lot_id'], unique=False)
    op.create_index(op.f('ix_git_commit_gitlab_commit_id'), 'git_commit', ['gitlab_commit_id'], unique=False)
    op.create_index(op.f('ix_git_commit_id'), 'git_commit', ['id'], unique=False)
    op.create_index(op.f('ix_git_commit_project_id'), 'git_commit', ['project_id'], unique=False)
    op.create_table('kpi_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_mrs_created', sa.Integer(), nullable=False),
    sa.Column('total_mrs_approved', sa.Integer(), nullable=False),
    sa.Column('total_mrs_merged', sa.Integer(), nullable=False),
    sa.Column('nb_developers', sa.Integer(), nullable=False),
    sa.Column('review_time_hours', sa.Float(), nullable=False),
    sa.Column('mr_rate_per_site', sa.Float(), nullable=False),
    sa.Column('approved_mr_rate', sa.Float(), nullable=False),
    sa.Column('merged_mr_rate', sa.Float(), nullable=False),
    sa.Column('commit_rate_per_site', sa.Float(), nullable=False),
    sa.Column('nb_commits_per_project', sa.Integer(), nullable=False),
    sa.Column('avg_review_time_hours', sa.Float(), nullable=False),
    sa.Column('delta_mr_rate', sa.Float(), nullable=True),
    sa.Column('delta_commit_rate', sa.Float(), nullable=True),
    sa.Column('delta_avg_review_time', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('kpi_definition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('approved_mr_rate    >= 0 AND approved_mr_rate    <= 1', name='chk_approved_rate'),
    sa.CheckConstraint('avg_review_time_hours >= 0', name='chk_review_time'),
    sa.CheckConstraint('commit_rate_per_site >= 0', name='chk_commit_rate'),
    sa.CheckConstraint('merged_mr_rate      >= 0 AND merged_mr_rate      <= 1', name='chk_merged_rate'),
    sa.CheckConstraint('mr_rate_per_site    >= 0', name='chk_mr_rate'),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['developer_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_definition_id'], ['kpi_definition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['extraction_lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpi_project_period_site_group', 'kpi_snapshot', ['project_id', 'period_id', 'site_id', 'group_id', 'developer_id'], unique=True)
    op.create_index(op.f('ix_kpi_snapshot_developer_id'), 'kpi_snapshot', ['developer_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_group_id'), 'kpi_snapshot', ['group_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_id'), 'kpi_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_kpi_definition_id'), 'kpi_snapshot', ['kpi_definition_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_lot_id'), 'kpi_snapshot', ['lot_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_period_id'), 'kpi_snapshot', ['period_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_project_id'), 'kpi_snapshot', ['project_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_site_id'), 'kpi_snapshot', ['site_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshot_snapshot_date'), 'kpi_snapshot', ['snapshot_date'], unique=False)
    op.create_table('merge_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gitlab_mr_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('opened', 'closed', 'merged', name='mrstateenum'), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at_gitlab', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('review_time_hours', sa.Float(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('total_changes', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('extraction_lot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_lot_id'], ['extraction_lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mr_draft_project', 'merge_request', ['is_draft', 'project_id'], unique=False)
    op.create_index('idx_mr_gitlab_project', 'merge_request', ['gitlab_mr_id', 'project_id'], unique=True)
    op.create_index('idx_mr_lot', 'merge_request', ['extraction_lot_id'], unique=False)
    op.create_index('idx_mr_project_created', 'merge_request', ['project_id', 'created_at_gitlab'], unique=False)
    op.create_index('idx_mr_state_project', 'merge_request', ['state', 'project_id'], unique=False)
    op.create_index(op.f('ix_merge_request_created_at_gitlab'), 'merge_request', ['created_at_gitlab'], unique=False)
    op.create_index(op.f('ix_merge_request_developer_id'), 'merge_request', ['developer_id'], unique=False)
    op.create_index(op.f('ix_merge_request_extraction_lot_id'), 'merge_request', ['extraction_lot_id'], unique=False)
    op.create_index(op.f('ix_merge_request_gitlab_mr_id'), 'merge_request', ['gitlab_mr_id'], unique=False)
    op.create_index(op.f('ix_merge_request_id'), 'merge_request', ['id'], unique=False)
    op.create_index(op.f('ix_merge_request_project_id'), 'merge_request', ['project_id'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('WARNING', 'CRITICAL', name='alertlevelenum'), nullable=False),
    sa.Column('kpi_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('kpi_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kpi_snapshot_id'], ['kpi_snapshot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threshold_id'], ['kpi_threshold.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_level', 'alert', ['level'], unique=False)
    op.create_index('idx_alert_resolved', 'alert', ['is_resolved'], unique=False)
    op.create_index('idx_alert_snapshot', 'alert', ['kpi_snapshot_id'], unique=False)
    op.create_index('idx_alert_threshold', 'alert', ['threshold_id'], unique=False)
    op.create_index('idx_alert_triggered_at', 'alert', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_acknowledged_by'), 'alert', ['acknowledged_by'], unique=False)
    op.create_index(op.f('ix_alert_id'), 'alert', ['id'], unique=False)
    op.create_index(op.f('ix_alert_is_resolved'), 'alert', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alert_kpi_snapshot_id'), 'alert', ['kpi_snapshot_id'], unique=False)
    op.create_index(op.f('ix_alert_level'), 'alert', ['level'], unique=False)
    op.create_index(op.f('ix_alert_threshold_id'), 'alert', ['threshold_id'], unique=False)
    op.create_index(op.f('ix_alert_triggered_at'), 'alert', ['triggered_at'], unique=False)
    op.create_table('commit_merge_request',
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('mr_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['git_commit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mr_id'], ['merge_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_id', 'mr_id'),
    sa.UniqueConstraint('commit_id', 'mr_id', name='uq_commit_mr')
    )
    op.create_index(op.f('ix_commit_merge_request_developer_id'), 'commit_merge_request', ['developer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commit_merge_request_developer_id'), table_name='commit_merge_request')
    op.drop_table('commit_merge_request')
    op.drop_index(op.f('ix_alert_triggered_at'), table_name='alert')
    op.drop_index(op.f('ix_alert_threshold_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_level'), table_name='alert')
    op.drop_index(op.f('ix_alert_kpi_snapshot_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_is_resolved'), table_name='alert')
    op.drop_index(op.f('ix_alert_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_acknowledged_by'), table_name='alert')
    op.drop_index('idx_alert_triggered_at', table_name='alert')
    op.drop_index('idx_alert_threshold', table_name='alert')
    op.drop_index('idx_alert_snapshot', table_name='alert')
    op.drop_index('idx_alert_resolved', table_name='alert')
    op.drop_index('idx_alert_level', table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_merge_request_project_id'), table_name='merge_request')
    op.drop_index(op.f('ix_merge_request_id'), table_name='merge_request')
    op.drop_index(op.f('ix_merge_request_gitlab_mr_id'), table_name='merge_request')
    op.drop_index(op.f('ix_merge_request_extraction_lot_id'), table_name='merge_request')
    op.drop_index(op.f('ix_merge_request_developer_id'), table_name='merge_request')
    op.drop_index(op.f('ix_merge_request_created_at_gitlab'), table_name='merge_request')
    op.drop_index('idx_mr_state_project', table_name='merge_request')
    op.drop_index('idx_mr_project_created', table_name='merge_request')
    op.drop_index('idx_mr_lot', table_name='merge_request')
    op.drop_index('idx_mr_gitlab_project', table_name='merge_request')
    op.drop_index('idx_mr_draft_project', table_name='merge_request')
    op.drop_table('merge_request')
    op.drop_index(op.f('ix_kpi_snapshot_snapshot_date'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_site_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_project_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_period_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_lot_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_kpi_definition_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_group_id'), table_name='kpi_snapshot')
    op.drop_index(op.f('ix_kpi_snapshot_developer_id'), table_name='kpi_snapshot')
    op.drop_index('idx_kpi_project_period_site_group', table_name='kpi_snapshot')
    op.drop_table('kpi_snapshot')
    op.drop_index(op.f('ix_git_commit_project_id'), table_name='git_commit')
    op.drop_index(op.f('ix_git_commit_id'), table_name='git_commit')
    op.drop_index(op.f('ix_git_commit_gitlab_commit_id'), table_name='git_commit')
    op.drop_index(op.f('ix_git_commit_extraction_lot_id'), table_name='git_commit')
    op.drop_index(op.f('ix_git_commit_developer_id'), table_name='git_commit')
    op.drop_index(op.f('ix_git_commit_authored_date'), table_name='git_commit')
    op.drop_index('idx_commit_sha_project', table_name='git_commit')
    op.drop_index('idx_commit_project_date', table_name='git_commit')
    op.drop_index('idx_commit_lot', table_name='git_commit')
    op.drop_index('idx_commit_developer_project', table_name='git_commit')
    op.drop_table('git_commit')
    op.drop_index(op.f('ix_period_filter_id'), table_name='period_filter')
    op.drop_index(op.f('ix_period_filter_dashboard_id'), table_name='period_filter')
    op.drop_index('idx_period_filter_type', table_name='period_filter')
    op.drop_index('idx_period_filter_dashboard', table_name='period_filter')
    op.drop_table('period_filter')
    op.drop_index(op.f('ix_kpi_threshold_project_id'), table_name='kpi_threshold')
    op.drop_index(op.f('ix_kpi_threshold_kpi_definition_id'), table_name='kpi_threshold')
    op.drop_index(op.f('ix_kpi_threshold_id'), table_name='kpi_threshold')
    op.drop_index(op.f('ix_kpi_threshold_dashboard_id'), table_name='kpi_threshold')
    op.drop_index(op.f('ix_kpi_threshold_created_by'), table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_dashboard_kpi', table_name='kpi_threshold')
    op.drop_table('kpi_threshold')
    op.drop_index(op.f('ix_developer_site_id'), table_name='developer')
    op.drop_index(op.f('ix_developer_project_id'), table_name='developer')
    op.drop_index(op.f('ix_developer_id'), table_name='developer')
    op.drop_index(op.f('ix_developer_created_by'), table_name='developer')
    op.drop_index('idx_developer_site', table_name='developer')
    op.drop_index('idx_developer_project', table_name='developer')
    op.drop_index('idx_developer_group_fk', table_name='developer')
    op.drop_index('idx_developer_gitlab_project', table_name='developer')
    op.drop_index('idx_developer_active', table_name='developer')
    op.drop_table('developer')
    op.drop_index(op.f('ix_extraction_lot_triggered_by'), table_name='extraction_lot')
    op.drop_index(op.f('ix_extraction_lot_project_id'), table_name='extraction_lot')
    op.drop_index(op.f('ix_extraction_lot_period_id'), table_name='extraction_lot')
    op.drop_index(op.f('ix_extraction_lot_id'), table_name='extraction_lot')
    op.drop_index('idx_lot_type_status', table_name='extraction_lot')
    op.drop_index('idx_lot_period_project', table_name='extraction_lot')
    op.drop_table('extraction_lot')
    op.drop_index(op.f('ix_developer_group_site_id'), table_name='developer_group')
    op.drop_index(op.f('ix_developer_group_project_id'), table_name='developer_group')
    op.drop_index(op.f('ix_developer_group_manager_id'), table_name='developer_group')
    op.drop_index(op.f('ix_developer_group_id'), table_name='developer_group')
    op.drop_index('idx_devgroup_project_site', table_name='developer_group')
    op.drop_index('idx_devgroup_manager', table_name='developer_group')
    op.drop_table('developer_group')
    op.drop_index(op.f('ix_dashboard_site_id'), table_name='dashboard')
    op.drop_index(op.f('ix_dashboard_project_id'), table_name='dashboard')
    op.drop_index(op.f('ix_dashboard_id'), table_name='dashboard')
    op.drop_index(op.f('ix_dashboard_created_by'), table_name='dashboard')
    op.drop_index('idx_dashboard_site', table_name='dashboard')
    op.drop_index('idx_dashboard_public', table_name='dashboard')
    op.drop_index('idx_dashboard_project', table_name='dashboard')
    op.drop_index('idx_dashboard_creator', table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_index(op.f('ix_project_site_id'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_gitlab_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_gitlab_config_id'), table_name='project')
    op.drop_index('idx_project_site', table_name='project')
    op.drop_index('idx_project_name_namespace', table_name='project')
    op.drop_index('idx_project_config', table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_created_at', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_site_name'), table_name='site')
    op.drop_index(op.f('ix_site_id'), table_name='site')
    op.drop_index('idx_site_name', table_name='site')
    op.drop_index('idx_site_country', table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_period_id'), table_name='period')
    op.drop_table('period')
    op.drop_index(op.f('ix_kpi_definition_id'), table_name='kpi_definition')
    op.drop_index(op.f('ix_kpi_definition_code'), table_name='kpi_definition')
    op.drop_index('idx_kpi_definition_code', table_name='kpi_definition')
    op.drop_index('idx_kpi_definition_active', table_name='kpi_definition')
    op.drop_table('kpi_definition')
    op.drop_index(op.f('ix_gitlab_config_id'), table_name='gitlab_config')
    op.drop_table('gitlab_config')
    op.drop_index(op.f('ix_app_user_login'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
