"""update_developer_models

Revision ID: 398f54aa2093
Revises: aa42fae20f3a
Create Date: 2026-03-30 04:03:34.680963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398f54aa2093'
down_revision: Union[str, Sequence[str], None] = 'aa42fae20f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # uq_commit_mr existe déjà en base — on skip avec IF NOT EXISTS via SQL direct
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_commit_mr'
            ) THEN
                ALTER TABLE commit_merge_request ADD CONSTRAINT uq_commit_mr UNIQUE (commit_id, mr_id);
            END IF;
        END $$;
    """)
    
    # Indexes — IF NOT EXISTS natif PostgreSQL
    op.execute("CREATE INDEX IF NOT EXISTS idx_developer_email ON developer (email)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_developer_gitlab_user_id ON developer (gitlab_user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_developer_gitlab_username ON developer (gitlab_username)")
    
    op.alter_column('kpi_snapshot', 'delta_nb_commits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kpi_snapshot', 'delta_nb_commits',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index('idx_developer_gitlab_username', table_name='developer')
    op.drop_index('idx_developer_gitlab_user_id', table_name='developer')
    op.drop_index('idx_developer_email', table_name='developer')
    op.drop_constraint('uq_commit_mr', 'commit_merge_request', type_='unique')
    # ### end Alembic commands ###
