"""lifecycle_management_refactor

Revision ID: 5af652e3cdb7
Revises: 6319549f694c
Create Date: 2026-05-08 20:39:45.237007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5af652e3cdb7'
down_revision: Union[str, Sequence[str], None] = '6319549f694c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_group_site')
    op.alter_column('developer', 'offboarding_date',
               existing_type=sa.DATE(),
               comment='Date de départ ou désactivation',
               existing_nullable=True)
    op.drop_index('idx_developer_gitlab_user_unique', table_name='developer', postgresql_where='(gitlab_user_id IS NOT NULL)')
    op.drop_index('idx_developer_group_id', table_name='developer')
    op.drop_index('idx_developer_site_id', table_name='developer')
    op.drop_constraint('developer_site_id_fkey', 'developer', type_='foreignkey')
    op.drop_constraint('developer_group_id_fkey', 'developer', type_='foreignkey')
    op.drop_column('developer', 'site_id')
    op.drop_column('developer', 'group_id')
    # -- DEVELOPER_PROJECT REFACTOR (SAUVETAGE DONNEES) --
    # 1. Supprimer l'ancienne PK composite
    op.drop_constraint('developer_project_pkey', 'developer_project', type_='primary')
    
    # 2. Ajouter la nouvelle PK auto-incrémentée (SERIAL gère la séquence et l'unicité)
    op.execute("ALTER TABLE developer_project ADD COLUMN id SERIAL PRIMARY KEY")
    
    # 3. Ajouter les colonnes de dates
    op.add_column('developer_project', sa.Column('start_date', sa.Date(), nullable=True, comment='Début de mission (si vide =joined_at)'))
    op.add_column('developer_project', sa.Column('end_date', sa.Date(), nullable=True, comment='Fin de mission (si vide = toujours actif)'))
    
    # 4. Rendre period_id nullable
    op.alter_column('developer_project', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_dev_project_developer', table_name='developer_project')
    op.drop_index('idx_dev_project_project', table_name='developer_project')
    op.create_index('idx_dev_project_dates', 'developer_project', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_dev_project_dev_period', 'developer_project', ['developer_id', 'period_id', 'is_active'], unique=False)
    op.create_index('idx_dev_project_proj_period', 'developer_project', ['project_id', 'period_id', 'is_active'], unique=False)
    op.create_index('idx_dev_project_unique', 'developer_project', ['developer_id', 'project_id', 'period_id'], unique=True)
    op.drop_constraint('developer_project_period_id_fkey', 'developer_project', type_='foreignkey')
    op.create_foreign_key(None, 'developer_project', 'period', ['period_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_developer_one_primary_site', table_name='developer_site', postgresql_where='(is_primary = true)')
    op.alter_column('extraction_lot', 'step_progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_lot', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extraction_lot', 'items_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Somme Commits + MRs',
               existing_nullable=False)
    op.alter_column('extraction_lot', 'api_calls_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extraction_lot', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_lot', 'metadata_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON des détails techniques',
               existing_nullable=True)
    op.drop_index('idx_kpi_snapshot_unique', table_name='kpi_snapshot')
    op.drop_index('idx_kpi_threshold_unique', table_name='kpi_threshold')
    op.alter_column('period', 'closure_summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Checklist de validation pré-clôture',
               existing_nullable=True)
    op.alter_column('period', 'headcount_snapshot',
               existing_type=sa.INTEGER(),
               comment='Nombre de devs actifs figé au moment de la clôture (règle 15j appliquée)',
               existing_comment='Nombre de devs actifs fige au moment de la cloture (regle 15j)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('period', 'headcount_snapshot',
               existing_type=sa.INTEGER(),
               comment='Nombre de devs actifs fige au moment de la cloture (regle 15j)',
               existing_comment='Nombre de devs actifs figé au moment de la clôture (règle 15j appliquée)',
               existing_nullable=True)
    op.alter_column('period', 'closure_summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Checklist de validation pré-clôture',
               existing_nullable=True)
    op.create_index('idx_kpi_threshold_unique', 'kpi_threshold', [sa.text("COALESCE(dashboard_id, '-1'::integer)"), sa.text("COALESCE(site_id, '-1'::integer)"), 'kpi_definition_id', 'threshold_type', 'project_id'], unique=True)
    op.create_index('idx_kpi_snapshot_unique', 'kpi_snapshot', ['project_id', 'period_id', sa.text("COALESCE(site_id, '-1'::integer)"), sa.text("COALESCE(group_id, '-1'::integer)"), sa.text("COALESCE(developer_id, '-1'::integer)")], unique=True)
    op.alter_column('extraction_lot', 'metadata_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON des détails techniques',
               existing_nullable=True)
    op.alter_column('extraction_lot', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_lot', 'api_calls_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('extraction_lot', 'items_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='Somme Commits + MRs',
               existing_nullable=False)
    op.alter_column('extraction_lot', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('extraction_lot', 'step_progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index('idx_developer_one_primary_site', 'developer_site', ['developer_id'], unique=True, postgresql_where='(is_primary = true)')
    op.drop_constraint(None, 'developer_project', type_='foreignkey')
    op.create_foreign_key('developer_project_period_id_fkey', 'developer_project', 'period', ['period_id'], ['id'])
    op.drop_index('idx_dev_project_unique', table_name='developer_project')
    op.drop_index('idx_dev_project_proj_period', table_name='developer_project')
    op.drop_index('idx_dev_project_dev_period', table_name='developer_project')
    op.drop_index('idx_dev_project_dates', table_name='developer_project')
    op.create_index('idx_dev_project_project', 'developer_project', ['project_id', 'is_active'], unique=False)
    op.create_index('idx_dev_project_developer', 'developer_project', ['developer_id', 'is_active'], unique=False)
    op.alter_column('developer_project', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('developer_project', 'end_date')
    op.drop_column('developer_project', 'start_date')
    op.drop_column('developer_project', 'id')
    op.add_column('developer', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Groupe actuel du développeur (FK directe — remplace developer_group_link M2M)'))
    op.add_column('developer', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Site actuel du développeur (FK directe — remplace DeveloperSite M2M)'))
    op.create_foreign_key('developer_group_id_fkey', 'developer', 'developer_group', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('developer_site_id_fkey', 'developer', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_developer_site_id', 'developer', ['site_id'], unique=False)
    op.create_index('idx_developer_group_id', 'developer', ['group_id'], unique=False)
    op.create_index('idx_developer_gitlab_user_unique', 'developer', ['gitlab_user_id'], unique=True, postgresql_where='(gitlab_user_id IS NOT NULL)')
    op.alter_column('developer', 'offboarding_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date de départ ou désactivation',
               existing_nullable=True)
    op.create_table('developer_group_site',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['developer_group.id'], name='developer_group_site_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name='developer_group_site_site_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'site_id', name='developer_group_site_pkey')
    )
    # ### end Alembic commands ###
