"""migration_m2m_developer_groups

Revision ID: 6319549f694c
Revises: 20c4b5a6b484
Create Date: 2026-04-19 18:07:18.870548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6319549f694c'
down_revision: Union[str, Sequence[str], None] = '20c4b5a6b484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_group_link',
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['developer_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('developer_id', 'group_id')
    )
    # 1. Ajout de site_id comme nullable d'abord
    op.add_column('developer_group', sa.Column('site_id', sa.Integer(), nullable=True))

    # 2. Migration des données depuis la table de jointure avant de la supprimer
    op.execute("""
        UPDATE developer_group 
        SET site_id = (
            SELECT site_id FROM developer_group_site 
            WHERE developer_group_site.group_id = developer_group.id 
            LIMIT 1
        )
    """)

    # 3. Fallback : si certains groupes n'ont pas de site, on leur affecte le premier site disponible 
    # (indispensable pour passer la contrainte NOT NULL)
    op.execute("UPDATE developer_group SET site_id = (SELECT id FROM site LIMIT 1) WHERE site_id IS NULL")

    # 4. Maintenant on peut mettre NOT NULL
    op.alter_column('developer_group', 'site_id', nullable=False)

    # 5. Ajout de la clé étrangère
    op.create_foreign_key('fk_developer_group_site', 'developer_group', 'site', ['site_id'], ['id'], ondelete='CASCADE')

    # 6. Suppression de l'ancienne table de jointure
    op.drop_table('developer_group_site')

    # 7. Nettoyage de la table developer (retrait de l'ancienne colonne group_id)
    op.drop_index('idx_developer_gitlab_user_unique', table_name='developer', postgresql_where='(gitlab_user_id IS NOT NULL)')
    op.drop_index('idx_developer_group', table_name='developer')
    op.drop_constraint('developer_group_id_fkey', 'developer', type_='foreignkey')
    op.drop_column('developer', 'group_id')

    # op.create_unique_constraint('uq_commit_mr', 'commit_merge_request', ['commit_id', 'mr_id'])
    op.drop_index('idx_developer_one_primary_site', table_name='developer_site', postgresql_where='(is_primary = true)')
    op.alter_column('kpi_snapshot', 'bus_factor',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kpi_snapshot', 'sprint_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kpi_snapshot', 'code_churn_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_kpi_snapshot_unique', table_name='kpi_snapshot')
    op.drop_index('idx_kpi_threshold_unique', table_name='kpi_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_kpi_threshold_unique', 'kpi_threshold', [sa.text("COALESCE(dashboard_id, '-1'::integer)"), sa.text("COALESCE(site_id, '-1'::integer)"), 'kpi_definition_id', 'threshold_type', 'project_id'], unique=True)
    op.create_index('idx_kpi_snapshot_unique', 'kpi_snapshot', ['project_id', 'period_id', sa.text("COALESCE(site_id, '-1'::integer)"), sa.text("COALESCE(group_id, '-1'::integer)"), sa.text("COALESCE(developer_id, '-1'::integer)")], unique=True)
    op.alter_column('kpi_snapshot', 'code_churn_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('kpi_snapshot', 'sprint_velocity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('kpi_snapshot', 'bus_factor',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index('idx_developer_one_primary_site', 'developer_site', ['developer_id'], unique=True, postgresql_where='(is_primary = true)')
    op.drop_constraint(None, 'developer_group', type_='foreignkey')
    op.drop_column('developer_group', 'site_id')
    op.add_column('developer', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('developer_group_id_fkey', 'developer', 'developer_group', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_developer_group', 'developer', ['group_id'], unique=False)
    op.create_index('idx_developer_gitlab_user_unique', 'developer', ['gitlab_user_id'], unique=True, postgresql_where='(gitlab_user_id IS NOT NULL)')
    # op.drop_constraint('uq_commit_mr', 'commit_merge_request', type_='unique')
    op.create_table('developer_group_site',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['developer_group.id'], name='developer_group_site_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name='developer_group_site_site_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'site_id', name='developer_group_site_pkey')
    )
    op.drop_table('developer_group_link')
    # ### end Alembic commands ###
