"""add_updated_at_to_merge_request

Revision ID: 6f7f7e920eb0
Revises: d1db7f36cece
Create Date: 2026-04-07 17:50:15.946099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7f7e920eb0'
down_revision: Union[str, Sequence[str], None] = 'd1db7f36cece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_request', sa.Column('updated_at_gitlab', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merge_request', 'updated_at_gitlab')
    op.alter_column('kpi_snapshot', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('kpi_snapshot', 'total_comments',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.drop_constraint('uq_commit_mr', 'commit_merge_request', type_='unique')
    # ### end Alembic commands ###
