"""add_developer_id_to_commit_merge_request

Revision ID: 8ba8dcf32940
Revises: 987867f3cce8
Create Date: 2026-03-09 15:53:25.407833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba8dcf32940'
down_revision: Union[str, Sequence[str], None] = '987867f3cce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
