"""add_developer_id_to_commit_merge_request

Revision ID: 987867f3cce8
Revises: 4f24920e38ef
Create Date: 2026-03-09 15:46:15.723582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987867f3cce8'
down_revision: Union[str, Sequence[str], None] = '4f24920e38ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_merge_request', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_commit_merge_request_developer_id'), 'commit_merge_request', ['developer_id'], unique=False)
    op.create_unique_constraint('uq_commit_mr', 'commit_merge_request', ['commit_id', 'mr_id'])
    op.create_foreign_key(None, 'commit_merge_request', 'developer', ['developer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commit_merge_request', type_='foreignkey')
    op.drop_constraint('uq_commit_mr', 'commit_merge_request', type_='unique')
    op.drop_index(op.f('ix_commit_merge_request_developer_id'), table_name='commit_merge_request')
    op.drop_column('commit_merge_request', 'developer_id')
    # ### end Alembic commands ###
