"""add missing columns

Revision ID: aa42fae20f3a
Revises: 4f1bea3d073d
Create Date: 2026-03-29 22:26:17.040894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa42fae20f3a'
down_revision: Union[str, Sequence[str], None] = '4f1bea3d073d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('kpi_value', sa.Float(), nullable=False))
    op.add_column('alert', sa.Column('threshold_value', sa.Float(), nullable=False))
    # ... [lignes intermédiaires conservées] ...
    op.add_column('alert', sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('alert', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alert', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.add_column('alert', sa.Column('threshold_id', sa.Integer(), nullable=False))
    op.add_column('alert', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('alert', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('alert', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('alert', 'level',
               existing_type=postgresql.ENUM('WARNING', 'CRITICAL', name='alertlevelenum'),
               nullable=False)
    op.alter_column('alert', 'kpi_snapshot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_alert_acknowledged_by', 'alert', ['acknowledged_by'], unique=False)
    op.create_index('idx_alert_dev_unresolved', 'alert', ['developer_id', 'is_resolved'], unique=False)
    op.create_index('idx_alert_developer', 'alert', ['developer_id'], unique=False)
    op.create_index('idx_alert_level', 'alert', ['level'], unique=False)
    op.create_index('idx_alert_resolved', 'alert', ['is_resolved'], unique=False)
    op.create_index('idx_alert_snapshot', 'alert', ['kpi_snapshot_id'], unique=False)
    op.create_index('idx_alert_threshold', 'alert', ['threshold_id'], unique=False)
    op.create_index('idx_alert_triggered_at', 'alert', ['triggered_at'], unique=False)
    op.create_index('idx_alert_unresolved_recent', 'alert', ['is_resolved', 'triggered_at'], unique=False)
    op.create_foreign_key(None, 'alert', 'app_user', ['acknowledged_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alert', 'developer', ['developer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alert', 'kpi_threshold', ['threshold_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_appuser_active', 'app_user', ['is_active'], unique=False)
    op.create_index('idx_appuser_group', 'app_user', ['group_id'], unique=False)
    op.create_index('idx_appuser_role', 'app_user', ['role'], unique=False)
    op.create_index('idx_appuser_site', 'app_user', ['site_id'], unique=False)
    
    # CORRECTION : Commenté car la contrainte existe déjà dans la base
    # op.create_unique_constraint('uq_commit_mr', 'commit_merge_request', ['commit_id', 'mr_id'])

    op.add_column('developer', sa.Column('gitlab_user_id', sa.Integer(), nullable=True))
    op.add_column('developer', sa.Column('gitlab_username', sa.String(length=255), nullable=True))
    op.add_column('developer', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('developer', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('developer', sa.Column('is_validated', sa.Boolean(), nullable=False, comment='False = extrait auto GitLab non encore validé par admin'))
    op.add_column('developer', sa.Column('is_bot', sa.Boolean(), nullable=False, comment='True = bot détecté automatiquement, exclu de tous les KPIs'))
    op.add_column('developer', sa.Column('is_external', sa.Boolean(), nullable=False))
    op.add_column('developer', sa.Column('auto_created', sa.Boolean(), nullable=False))
    op.add_column('developer', sa.Column('source', sa.String(length=50), nullable=False, comment="Origine : 'gitlab_extraction' | 'manual' | 'csv_import'"))
    op.add_column('developer', sa.Column('onboarding_date', sa.Date(), nullable=True))
    op.add_column('developer', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('developer', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('developer', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('developer', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('developer', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('idx_developer_active', 'developer', ['is_active'], unique=False)
    op.create_index('idx_developer_bot', 'developer', ['is_bot'], unique=False)
    op.create_index('idx_developer_external', 'developer', ['is_external'], unique=False)
    op.create_index('idx_developer_group', 'developer', ['group_id'], unique=False)
    op.create_index('idx_developer_kpi_filter', 'developer', ['is_validated', 'is_bot', 'is_active'], unique=False)
    op.create_index('idx_developer_source', 'developer', ['source'], unique=False)
    op.create_index('idx_developer_validated', 'developer', ['is_validated'], unique=False)
    op.create_foreign_key(None, 'developer', 'app_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('developer_group', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('developer_group', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_devgroup_manager', 'developer_group', ['manager_id'], unique=False)
    op.create_index('idx_devgroup_site', 'developer_group', ['site_id'], unique=False)
    op.create_index('idx_devgroup_site_name', 'developer_group', ['site_id', 'name'], unique=False)
    op.add_column('developer_project', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('developer_project', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('developer_project', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('developer_project', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_dev_project_developer', 'developer_project', ['developer_id', 'is_active'], unique=False)
    op.create_index('idx_dev_project_project', 'developer_project', ['project_id', 'is_active'], unique=False)
    # op.drop_index('idx_developer_one_primary_site', table_name='developer_site', postgresql_where='(is_primary = true)')
    op.add_column('extraction_lot', sa.Column('extraction_type', sa.Enum('REALTIME', 'MONTHLY', name='extractiontypeenum'), nullable=False, comment='REALTIME = à la demande | MONTHLY = clôture mensuelle'))
    op.add_column('extraction_lot', sa.Column('generated_file', sa.String(length=500), nullable=True))
    op.add_column('extraction_lot', sa.Column('md5sum', sa.String(length=64), nullable=True))
    op.add_column('extraction_lot', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('extraction_lot', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('extraction_lot', sa.Column('triggered_by', sa.Integer(), nullable=True))
    op.add_column('extraction_lot', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('extraction_lot', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('extraction_lot', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', name='extractionstatusenum'),
               nullable=False)
    op.alter_column('extraction_lot', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('extraction_lot', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_lot_completed_at', 'extraction_lot', ['completed_at'], unique=False)
    op.create_index('idx_lot_period_project', 'extraction_lot', ['period_id', 'project_id'], unique=False)
    op.create_index('idx_lot_project_status', 'extraction_lot', ['project_id', 'status'], unique=False)
    op.create_index('idx_lot_triggered_by', 'extraction_lot', ['triggered_by'], unique=False)
    op.create_index('idx_lot_type_status', 'extraction_lot', ['extraction_type', 'status'], unique=False)
    op.create_foreign_key(None, 'extraction_lot', 'app_user', ['triggered_by'], ['id'], ondelete='SET NULL')
    op.add_column('git_commit', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('git_commit', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('git_commit', sa.Column('authored_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('git_commit', sa.Column('committed_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('git_commit', sa.Column('additions', sa.Integer(), nullable=False))
    op.add_column('git_commit', sa.Column('deletions', sa.Integer(), nullable=False))
    op.add_column('git_commit', sa.Column('total_changes', sa.Integer(), nullable=False))
    op.add_column('git_commit', sa.Column('is_merge_commit', sa.Boolean(), nullable=False))
    op.add_column('git_commit', sa.Column('branch_name', sa.String(length=255), nullable=True))
    op.add_column('git_commit', sa.Column('author_name', sa.String(length=255), nullable=True))
    op.add_column('git_commit', sa.Column('author_email', sa.String(length=255), nullable=True))
    op.add_column('git_commit', sa.Column('extraction_lot_id', sa.Integer(), nullable=True))
    op.add_column('git_commit', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('git_commit', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('git_commit', 'gitlab_commit_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('git_commit', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_commit_branch', 'git_commit', ['project_id', 'branch_name'], unique=False)
    op.create_index('idx_commit_developer_date', 'git_commit', ['developer_id', 'authored_date'], unique=False)
    op.create_index('idx_commit_developer_project', 'git_commit', ['developer_id', 'project_id'], unique=False)
    op.create_index('idx_commit_lot', 'git_commit', ['extraction_lot_id'], unique=False)
    op.create_index('idx_commit_project_date_merge', 'git_commit', ['project_id', 'authored_date', 'is_merge_commit'], unique=False)
    op.create_index('idx_commit_sha_project', 'git_commit', ['gitlab_commit_id', 'project_id'], unique=True)
    op.create_index('idx_commit_unmatched', 'git_commit', ['project_id', 'developer_id'], unique=False)
    op.create_foreign_key(None, 'git_commit', 'extraction_lot', ['extraction_lot_id'], ['id'], ondelete='SET NULL')
    op.add_column('gitlab_config', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('gitlab_config', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('gitlab_config', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('gitlab_config', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gitlab_config', 'domain',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('gitlab_config', 'token',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.create_index('idx_gitlab_config_active', 'gitlab_config', ['is_active'], unique=False)
    op.create_index('idx_gitlab_config_site', 'gitlab_config', ['site_id'], unique=False)
    op.alter_column('kpi_definition', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kpi_definition', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_kpi_def_active', 'kpi_definition', ['is_active'], unique=False)
    op.create_index('idx_kpi_def_level', 'kpi_definition', ['aggregation_level'], unique=False)
    op.add_column('kpi_snapshot', sa.Column('snapshot_date', sa.Date(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('total_commits', sa.Integer(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('total_mrs_created', sa.Integer(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('total_mrs_approved', sa.Integer(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('total_mrs_merged', sa.Integer(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('nb_developers', sa.Integer(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('review_time_hours', sa.Float(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('mr_rate_per_site', sa.Float(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('mr_rate_per_ticket', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('approved_mr_rate', sa.Float(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('merged_mr_rate', sa.Float(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('commit_rate_per_site', sa.Float(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('nb_commits_per_project', sa.Integer(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('avg_review_time_hours', sa.Float(), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('delta_mr_rate', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('delta_approved_mr_rate', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('delta_merged_mr_rate', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('delta_commit_rate', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('delta_nb_commits', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('delta_avg_review_time', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('developer_score', sa.Float(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('score_rank_in_site', sa.Integer(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('kpi_snapshot', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('kpi_snapshot', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('kpi_snapshot', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kpi_snapshot', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_snapshot_date', 'kpi_snapshot', ['snapshot_date'], unique=False)
    op.create_index('idx_snapshot_dev_rank', 'kpi_snapshot', ['site_id', 'period_id', 'score_rank_in_site'], unique=False)
    op.create_index('idx_snapshot_developer', 'kpi_snapshot', ['developer_id'], unique=False)
    op.create_index('idx_snapshot_group', 'kpi_snapshot', ['group_id'], unique=False)
    op.create_index('idx_snapshot_lot', 'kpi_snapshot', ['lot_id'], unique=False)
    op.create_index('idx_snapshot_period_site', 'kpi_snapshot', ['period_id', 'site_id'], unique=False)
    op.create_index('idx_snapshot_project_period', 'kpi_snapshot', ['project_id', 'period_id'], unique=False)
    op.create_index('idx_snapshot_site', 'kpi_snapshot', ['site_id'], unique=False)
    op.create_foreign_key(None, 'kpi_snapshot', 'developer', ['developer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kpi_snapshot', 'extraction_lot', ['lot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kpi_snapshot', 'developer_group', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kpi_snapshot', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.add_column('kpi_threshold', sa.Column('warning_value', sa.Float(), nullable=False))
    op.add_column('kpi_threshold', sa.Column('critical_value', sa.Float(), nullable=False))
    op.add_column('kpi_threshold', sa.Column('threshold_type', sa.Enum('REALTIME', 'MONTHLY', name='thresholdtypeenum'), nullable=False, comment='REALTIME = seuil temps réel | MONTHLY = seuil clôture mensuelle'))
    op.add_column('kpi_threshold', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('kpi_threshold', sa.Column('dashboard_id', sa.Integer(), nullable=True))
    op.add_column('kpi_threshold', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('kpi_threshold', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('kpi_threshold', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('kpi_threshold', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kpi_threshold', 'kpi_definition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_kpi_threshold_creator', 'kpi_threshold', ['created_by'], unique=False)
    op.create_index('idx_kpi_threshold_dashboard', 'kpi_threshold', ['dashboard_id'], unique=False)
    op.create_index('idx_kpi_threshold_definition', 'kpi_threshold', ['kpi_definition_id'], unique=False)
    op.create_index('idx_kpi_threshold_project', 'kpi_threshold', ['project_id'], unique=False)
    op.create_index('idx_kpi_threshold_site', 'kpi_threshold', ['site_id'], unique=False)
    op.create_index('idx_kpi_threshold_type', 'kpi_threshold', ['threshold_type'], unique=False)
    op.drop_constraint('kpi_threshold_kpi_definition_id_fkey', 'kpi_threshold', type_='foreignkey')
    op.create_foreign_key(None, 'kpi_threshold', 'kpi_definition', ['kpi_definition_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'kpi_threshold', 'dashboard', ['dashboard_id'], ['id'], ondelete='CASCADE')
    # ... [autres contraintes étrangères kpi_threshold] ...
    op.create_foreign_key(None, 'kpi_threshold', 'app_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kpi_threshold', 'site', ['site_id'], ['id'], ondelete='CASCADE')
    op.add_column('merge_request', sa.Column('title', sa.String(length=500), nullable=False))
    op.add_column('merge_request', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('merge_request', sa.Column('is_draft', sa.Boolean(), nullable=False))
    op.add_column('merge_request', sa.Column('source_branch', sa.String(length=255), nullable=True))
    op.add_column('merge_request', sa.Column('target_branch', sa.String(length=255), nullable=True))
    op.add_column('merge_request', sa.Column('created_at_gitlab', sa.DateTime(timezone=True), nullable=False))
    op.add_column('merge_request', sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('merge_request', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('merge_request', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('merge_request', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('merge_request', sa.Column('review_time_hours', sa.Float(), nullable=True))
    op.add_column('merge_request', sa.Column('additions', sa.Integer(), nullable=True))
    op.add_column('merge_request', sa.Column('deletions', sa.Integer(), nullable=True))
    op.add_column('merge_request', sa.Column('total_changes', sa.Integer(), nullable=True))
    op.add_column('merge_request', sa.Column('author_name', sa.String(length=255), nullable=True))
    op.add_column('merge_request', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('merge_request', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('merge_request', sa.Column('extraction_lot_id', sa.Integer(), nullable=True))
    op.add_column('merge_request', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('merge_request', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('merge_request', 'gitlab_mr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('merge_request', 'state',
               existing_type=postgresql.ENUM('opened', 'closed', 'merged', name='mrstateenum'),
               nullable=False)
    op.alter_column('merge_request', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_mr_approved', 'merge_request', ['approved', 'project_id'], unique=False)
    op.create_index('idx_mr_developer_date', 'merge_request', ['developer_id', 'created_at_gitlab'], unique=False)
    op.create_index('idx_mr_draft_project', 'merge_request', ['is_draft', 'project_id'], unique=False)
    op.create_index('idx_mr_gitlab_project', 'merge_request', ['gitlab_mr_id', 'project_id'], unique=True)
    op.create_index('idx_mr_lot', 'merge_request', ['extraction_lot_id'], unique=False)
    op.create_index('idx_mr_project_created', 'merge_request', ['project_id', 'created_at_gitlab'], unique=False)
    op.create_index('idx_mr_reviewer', 'merge_request', ['reviewer_id', 'project_id'], unique=False)
    op.create_index('idx_mr_state_project', 'merge_request', ['state', 'project_id'], unique=False)
    op.create_index('idx_mr_target_branch', 'merge_request', ['project_id', 'target_branch'], unique=False)
    op.create_index('idx_mr_unmatched', 'merge_request', ['project_id', 'developer_id'], unique=False)
    op.create_foreign_key(None, 'merge_request', 'developer', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'merge_request', 'developer', ['developer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'merge_request', 'extraction_lot', ['extraction_lot_id'], ['id'], ondelete='SET NULL')
    op.add_column('period', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('period', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('period', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('period_year_month_key', 'period', type_='unique')
    op.create_index('idx_period_status', 'period', ['status'], unique=False)
    op.create_index('idx_period_year_month', 'period', ['year', 'month'], unique=False)
    op.create_unique_constraint('uq_period_year_month', 'period', ['year', 'month'])
    op.add_column('project', sa.Column('namespace', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('description', sa.String(), nullable=True))
    op.add_column('project', sa.Column('default_branch', sa.String(length=100), nullable=True))
    op.add_column('project', sa.Column('last_commit_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('project', 'path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('idx_project_active', 'project', ['is_active'], unique=False)
    op.create_index('idx_project_config', 'project', ['gitlab_config_id'], unique=False)
    op.create_index('idx_project_last_commit', 'project', ['last_commit_date'], unique=False)
    op.create_index('idx_project_name_namespace', 'project', ['name', 'namespace'], unique=False)
    op.alter_column('site', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('site', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_site_active', 'site', ['is_active'], unique=False)
    op.create_index('idx_site_country', 'site', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_site_country', table_name='site')
    op.drop_index('idx_site_active', table_name='site')
    op.alter_column('site', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('site', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_project_name_namespace', table_name='project')
    op.drop_index('idx_project_last_commit', table_name='project')
    op.drop_index('idx_project_config', table_name='project')
    op.drop_index('idx_project_active', table_name='project')
    op.alter_column('project', 'path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'created_at')
    op.drop_column('project', 'last_commit_date')
    op.drop_column('project', 'default_branch')
    # ... [autres colonnes projet] ...
    op.drop_column('project', 'description')
    op.drop_column('project', 'namespace')
    op.drop_constraint('uq_period_year_month', 'period', type_='unique')
    op.drop_index('idx_period_year_month', table_name='period')
    op.drop_index('idx_period_status', table_name='period')
    op.create_unique_constraint('period_year_month_key', 'period', ['year', 'month'])
    op.drop_column('period', 'updated_at')
    op.drop_column('period', 'created_at')
    op.drop_column('period', 'closed_at')
    op.drop_constraint(None, 'merge_request', type_='foreignkey')
    op.drop_constraint(None, 'merge_request', type_='foreignkey')
    op.drop_constraint(None, 'merge_request', type_='foreignkey')
    op.drop_index('idx_mr_unmatched', table_name='merge_request')
    op.drop_index('idx_mr_target_branch', table_name='merge_request')
    op.drop_index('idx_mr_state_project', table_name='merge_request')
    op.drop_index('idx_mr_reviewer', table_name='merge_request')
    op.drop_index('idx_mr_project_created', table_name='merge_request')
    op.drop_index('idx_mr_lot', table_name='merge_request')
    op.drop_index('idx_mr_gitlab_project', table_name='merge_request')
    op.drop_index('idx_mr_draft_project', table_name='merge_request')
    op.drop_index('idx_mr_developer_date', table_name='merge_request')
    op.drop_index('idx_mr_approved', table_name='merge_request')
    op.alter_column('merge_request', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('merge_request', 'state',
               existing_type=postgresql.ENUM('opened', 'closed', 'merged', name='mrstateenum'),
               nullable=True)
    op.alter_column('merge_request', 'gitlab_mr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('merge_request', 'updated_at')
    op.drop_column('merge_request', 'created_at')
    op.drop_column('merge_request', 'extraction_lot_id')
    op.drop_column('merge_request', 'reviewer_id')
    op.drop_column('merge_request', 'developer_id')
    op.drop_column('merge_request', 'author_name')
    op.drop_column('merge_request', 'total_changes')
    op.drop_column('merge_request', 'deletions')
    op.drop_column('merge_request', 'additions')
    op.drop_column('merge_request', 'review_time_hours')
    op.drop_column('merge_request', 'approved')
    op.drop_column('merge_request', 'approved_at')
    op.drop_column('merge_request', 'closed_at')
    op.drop_column('merge_request', 'merged_at')
    op.drop_column('merge_request', 'created_at_gitlab')
    op.drop_column('merge_request', 'target_branch')
    op.drop_column('merge_request', 'source_branch')
    op.drop_column('merge_request', 'is_draft')
    op.drop_column('merge_request', 'description')
    op.drop_column('merge_request', 'title')
    op.drop_constraint(None, 'kpi_threshold', type_='foreignkey')
    op.drop_constraint(None, 'kpi_threshold', type_='foreignkey')
    op.drop_constraint(None, 'kpi_threshold', type_='foreignkey')
    op.drop_constraint(None, 'kpi_threshold', type_='foreignkey')
    op.create_foreign_key('kpi_threshold_kpi_definition_id_fkey', 'kpi_threshold', 'kpi_definition', ['kpi_definition_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_kpi_threshold_type', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_site', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_project', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_definition', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_dashboard', table_name='kpi_threshold')
    op.drop_index('idx_kpi_threshold_creator', table_name='kpi_threshold')
    op.alter_column('kpi_threshold', 'kpi_definition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kpi_threshold', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('kpi_threshold', 'updated_at')
    op.drop_column('kpi_threshold', 'created_at')
    op.drop_column('kpi_threshold', 'created_by')
    op.drop_column('kpi_threshold', 'dashboard_id')
    op.drop_column('kpi_threshold', 'site_id')
    op.drop_column('kpi_threshold', 'threshold_type')
    op.drop_column('kpi_threshold', 'critical_value')
    op.drop_column('kpi_threshold', 'warning_value')
    
    # Correction : Commenté pour correspondre au upgrade
    # op.drop_constraint('uq_commit_mr', 'commit_merge_request', type_='unique')

    op.drop_constraint(None, 'kpi_snapshot', type_='foreignkey')
    op.drop_constraint(None, 'kpi_snapshot', type_='foreignkey')
    op.drop_constraint(None, 'kpi_snapshot', type_='foreignkey')
    op.drop_constraint(None, 'kpi_snapshot', type_='foreignkey')
    op.drop_index('idx_snapshot_site', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_project_period', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_period_site', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_lot', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_group', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_developer', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_dev_rank', table_name='kpi_snapshot')
    op.drop_index('idx_snapshot_date', table_name='kpi_snapshot')
    op.alter_column('kpi_snapshot', 'period_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kpi_snapshot', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('kpi_snapshot', 'updated_at')
    op.drop_column('kpi_snapshot', 'created_at')
    op.drop_column('kpi_snapshot', 'developer_id')
    op.drop_column('kpi_snapshot', 'group_id')
    op.drop_column('kpi_snapshot', 'site_id')
    op.drop_column('kpi_snapshot', 'lot_id')
    op.drop_column('kpi_snapshot', 'score_rank_in_site')
    op.drop_column('kpi_snapshot', 'developer_score')
    op.drop_column('kpi_snapshot', 'delta_avg_review_time')
    op.drop_column('kpi_snapshot', 'delta_nb_commits')
    op.drop_column('kpi_snapshot', 'delta_commit_rate')
    op.drop_column('kpi_snapshot', 'delta_merged_mr_rate')
    op.drop_column('kpi_snapshot', 'delta_approved_mr_rate')
    op.drop_column('kpi_snapshot', 'delta_mr_rate')
    op.drop_column('kpi_snapshot', 'avg_review_time_hours')
    op.drop_column('kpi_snapshot', 'nb_commits_per_project')
    op.drop_column('kpi_snapshot', 'commit_rate_per_site')
    op.drop_column('kpi_snapshot', 'merged_mr_rate')
    op.drop_column('kpi_snapshot', 'approved_mr_rate')
    op.drop_column('kpi_snapshot', 'mr_rate_per_ticket')
    op.drop_column('kpi_snapshot', 'mr_rate_per_site')
    op.drop_column('kpi_snapshot', 'review_time_hours')
    op.drop_column('kpi_snapshot', 'nb_developers')
    op.drop_column('kpi_snapshot', 'total_mrs_merged')
    op.drop_column('kpi_snapshot', 'total_mrs_approved')
    # ... [Fin du fichier] ...
    # ### end Alembic commands ###