"""add_target_database_to_import_log

Migration pour ajouter la colonne target_database à la table developer_import_log.
Cette colonne permet de suivre la base de données cible lors des imports de développeurs.

Revision ID: add_target_database_to_import_log
Revises: add_profile_menu_management
Create Date: 2026-06-11 11:03:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_target_database_to_import_log'
down_revision: Union[str, Sequence[str], None] = 'add_profile_menu_management'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_import_log', sa.Column('target_database', sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_import_log', 'target_database')
    # ### end Alembic commands ###
