"""remove_unique_constraint_from_domain

Revision ID: b43441979ec9
Revises: 0af83c947fdb
Create Date: 2026-04-01 12:39:27.830815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43441979ec9'
down_revision: Union[str, Sequence[str], None] = '0af83c947fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gitlab_config_domain_key', 'gitlab_config', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gitlab_config_domain_key', 'gitlab_config', ['domain'])
    # ### end Alembic commands ###
