"""add_missing_timestamps_group_link

Revision ID: c4ba0ad89dc2
Revises: 055646d7e82b
Create Date: 2026-05-09 18:31:54.041812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ba0ad89dc2'
down_revision: Union[str, Sequence[str], None] = '055646d7e82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_group_link', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('developer_group_link', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('developer_group_link', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='False = affectation clôturée',
               existing_comment='False = affectation cloturee',
               existing_nullable=False)
    op.alter_column('developer_group_link', 'start_date',
               existing_type=sa.DATE(),
               comment="Date d'entrée dans l'équipe",
               existing_comment="Date d'entree dans l'equipe",
               existing_nullable=True)
    op.alter_column('developer_group_link', 'end_date',
               existing_type=sa.DATE(),
               comment="Date de sortie (NULL = encore dans l'équipe)",
               existing_comment="Date de sortie (NULL = encore dans l'equipe)",
               existing_nullable=True)
    op.alter_column('developer_site', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='False = affectation clôturée (transfert ou départ)',
               existing_comment='False = affectation cloturee (transfert ou depart)',
               existing_nullable=False)
    op.alter_column('developer_site', 'start_date',
               existing_type=sa.DATE(),
               comment="Date de début d'affectation au site",
               existing_comment="Date de debut d'affectation au site",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developer_site', 'start_date',
               existing_type=sa.DATE(),
               comment="Date de debut d'affectation au site",
               existing_comment="Date de début d'affectation au site",
               existing_nullable=True)
    op.alter_column('developer_site', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='False = affectation cloturee (transfert ou depart)',
               existing_comment='False = affectation clôturée (transfert ou départ)',
               existing_nullable=False)
    op.alter_column('developer_group_link', 'end_date',
               existing_type=sa.DATE(),
               comment="Date de sortie (NULL = encore dans l'equipe)",
               existing_comment="Date de sortie (NULL = encore dans l'équipe)",
               existing_nullable=True)
    op.alter_column('developer_group_link', 'start_date',
               existing_type=sa.DATE(),
               comment="Date d'entree dans l'equipe",
               existing_comment="Date d'entrée dans l'équipe",
               existing_nullable=True)
    op.alter_column('developer_group_link', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='False = affectation cloturee',
               existing_comment='False = affectation clôturée',
               existing_nullable=False)
    op.drop_column('developer_group_link', 'updated_at')
    op.drop_column('developer_group_link', 'created_at')
    # ### end Alembic commands ###
