"""multi_site_group

Revision ID: d1db7f36cece
Revises: b43441979ec9
Create Date: 2026-04-01 15:04:03.392240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1db7f36cece'
down_revision: Union[str, Sequence[str], None] = 'b43441979ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_group_site',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['developer_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'site_id')
    )
    # Transfer existing site associations to the new table
    op.execute("INSERT INTO developer_group_site (group_id, site_id) SELECT id, site_id FROM developer_group WHERE site_id IS NOT NULL")
    
    op.drop_index('idx_devgroup_site', table_name='developer_group')
    op.drop_index('idx_devgroup_site_name', table_name='developer_group')
    op.drop_constraint('developer_group_site_id_fkey', 'developer_group', type_='foreignkey')
    op.drop_column('developer_group', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_group', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('developer_group_site_id_fkey', 'developer_group', 'site', ['site_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_devgroup_site_name', 'developer_group', ['site_id', 'name'], unique=False)
    op.create_index('idx_devgroup_site', 'developer_group', ['site_id'], unique=False)
    # Transfer data back from the association table
    op.execute("UPDATE developer_group SET site_id = (SELECT site_id FROM developer_group_site WHERE developer_group_site.group_id = developer_group.id LIMIT 1)")
    
    op.drop_table('developer_group_site')
    # ### end Alembic commands ###
